
## JPA

spring.datasource.url=jdbc:postgresql://localhost:5432/invisibleurl
spring.datasource.username=invisibleprogrammer
spring.datasource.password=invisiblepassword

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

# For debugging purposes only
#spring.jpa.show-sql: true

